# Generated by Django 5.0.6 on 2024-08-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=60)),
                ('price', models.FloatField()),
                ('pid', models.IntegerField()),
                ('pur_date', models.DateField()),
            ],
        ),
    ]
